# Generated by Django 4.2.2 on 2023-06-11 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbike', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.CharField(default='xd', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(max_length=500),
        ),
    ]
